"use client";

import "~/styles/globals.css";
import { Header, Footer } from "~/app/components";
import { useGetCustomerQuery } from "~/redux/services/customer/customer-api";
import { getCookie } from "~/utils/cookie";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ClientLayout({ children }) {
  const accessToken = getCookie("accessToken");

  if (accessToken) {
    useGetCustomerQuery(accessToken);
    console.log(accessToken);
  }

  return (
    <>
      <Header />
      <div>{children}</div>
      <Footer />
    </>
  );
}
