"use client";

import "~/styles/globals.css";
import { getCookie } from "cookies-next";
import { useGetEmployeeQuery } from "~/redux/services/employee/employee";
import jwtDecode from "jwt-decode";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ClientLayout({ children }) {
  const accessToken = getCookie("accessToken");

  if (accessToken) {
    const jwt = jwtDecode(accessToken);
    if (jwt.role === "Employee") {
      useGetEmployeeQuery(accessToken);
    }
  }

  return children;
}
