import "~/styles/globals.css";
import { inter } from "./fonts";
import { Header, Footer } from "./components";

import Providers from "~/redux/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body suppressHydrationWarning={true} className={inter.className}>
          <Header />
          <div>{children}</div>
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
