import "~/styles/globals.css";
import { inter } from "./fonts";

import { Header, Footer } from "~/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
